flags: {}
packages:
- '.'
- ../protolude
extra-deps:
- control-monad-omega-0.3.1
- semiring-simple-1.0.0.1
- servant-0.5
- servant-docs-0.5
- servant-server-0.5
- string-conv-0.1
- text-1.2.2.0
resolver: lts-5.8
